2025-08-02 17:56:38.366 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/google/__init__.py:2: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  __import__('pkg_resources').declare_namespace(__name__)

2025-08-02 17:56:55.593 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.1 is exactly one major version older than the runtime version 6.31.1 at pyatv/protocols/mrp/protobuf/ProtocolMessage.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(

2025-08-02 17:56:55.600 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.1 is exactly one major version older than the runtime version 6.31.1 at pyatv/protocols/mrp/protobuf/AudioFadeMessage.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(

2025-08-02 17:56:55.605 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.1 is exactly one major version older than the runtime version 6.31.1 at pyatv/protocols/mrp/protobuf/PlayerPath.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(

2025-08-02 17:56:55.608 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.1 is exactly one major version older than the runtime version 6.31.1 at pyatv/protocols/mrp/protobuf/Origin.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(

2025-08-02 17:56:55.612 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.1 is exactly one major version older than the runtime version 6.31.1 at pyatv/protocols/mrp/protobuf/DeviceInfoMessage.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(

2025-08-02 17:56:55.617 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.1 is exactly one major version older than the runtime version 6.31.1 at pyatv/protocols/mrp/protobuf/Common.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(

2025-08-02 17:56:55.625 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.1 is exactly one major version older than the runtime version 6.31.1 at pyatv/protocols/mrp/protobuf/NowPlayingClient.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(

2025-08-02 17:56:55.630 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.1 is exactly one major version older than the runtime version 6.31.1 at pyatv/protocols/mrp/protobuf/NowPlayingPlayer.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(

2025-08-02 17:56:55.643 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.1 is exactly one major version older than the runtime version 6.31.1 at pyatv/protocols/mrp/protobuf/AudioFadeResponseMessage.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(

2025-08-02 17:56:55.650 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.1 is exactly one major version older than the runtime version 6.31.1 at pyatv/protocols/mrp/protobuf/ClientUpdatesConfigMessage.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(

2025-08-02 17:56:55.653 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.1 is exactly one major version older than the runtime version 6.31.1 at pyatv/protocols/mrp/protobuf/ConfigureConnectionMessage.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(

2025-08-02 17:56:55.658 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.1 is exactly one major version older than the runtime version 6.31.1 at pyatv/protocols/mrp/protobuf/CryptoPairingMessage.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(

2025-08-02 17:56:55.663 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.1 is exactly one major version older than the runtime version 6.31.1 at pyatv/protocols/mrp/protobuf/GenericMessage.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(

2025-08-02 17:56:55.668 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.1 is exactly one major version older than the runtime version 6.31.1 at pyatv/protocols/mrp/protobuf/GetKeyboardSessionMessage.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(

2025-08-02 17:56:55.674 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.1 is exactly one major version older than the runtime version 6.31.1 at pyatv/protocols/mrp/protobuf/GetRemoteTextInputSessionMessage.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(

2025-08-02 17:56:55.678 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.1 is exactly one major version older than the runtime version 6.31.1 at pyatv/protocols/mrp/protobuf/GetVolumeMessage.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(

2025-08-02 17:56:55.683 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.1 is exactly one major version older than the runtime version 6.31.1 at pyatv/protocols/mrp/protobuf/GetVolumeResultMessage.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(

2025-08-02 17:56:55.692 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.1 is exactly one major version older than the runtime version 6.31.1 at pyatv/protocols/mrp/protobuf/KeyboardMessage.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(

2025-08-02 17:56:55.699 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.1 is exactly one major version older than the runtime version 6.31.1 at pyatv/protocols/mrp/protobuf/ModifyOutputContextRequestMessage.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(

2025-08-02 17:56:55.705 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.1 is exactly one major version older than the runtime version 6.31.1 at pyatv/protocols/mrp/protobuf/NotificationMessage.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(

2025-08-02 17:59:25.367 WARNING (MainThread) [homeassistant.helpers.translation] Failed to load integration for translation: Invalid domain shelly.number
2025-08-02 17:59:25.377 WARNING (MainThread) [homeassistant.helpers.translation] Failed to load integration for translation: Invalid domain mobile_app.notify
2025-08-02 17:59:25.377 WARNING (MainThread) [homeassistant.helpers.translation] Failed to load integration for translation: Invalid domain backup.event
2025-08-02 17:59:25.378 WARNING (MainThread) [homeassistant.helpers.translation] Failed to load integration for translation: Invalid domain sun.binary_sensor
2025-08-02 17:59:25.378 WARNING (MainThread) [homeassistant.helpers.translation] Failed to load integration for translation: Invalid domain shelly.valve
2025-08-02 17:59:25.378 WARNING (MainThread) [homeassistant.helpers.translation] Failed to load integration for translation: Invalid domain shelly.cover
2025-08-02 17:59:25.378 WARNING (MainThread) [homeassistant.helpers.translation] Failed to load integration for translation: Invalid domain hassio.binary_sensor
2025-08-02 17:59:25.378 WARNING (MainThread) [homeassistant.helpers.translation] Failed to load integration for translation: Invalid domain homeassistant.scene
2025-08-02 17:59:25.379 WARNING (MainThread) [homeassistant.helpers.translation] Failed to load integration for translation: Invalid domain shelly.sensor
2025-08-02 17:59:25.379 WARNING (MainThread) [homeassistant.helpers.translation] Failed to load integration for translation: Invalid domain hassio.update
2025-08-02 17:59:25.379 WARNING (MainThread) [homeassistant.helpers.translation] Failed to load integration for translation: Invalid domain backup.sensor
2025-08-02 17:59:25.379 WARNING (MainThread) [homeassistant.helpers.translation] Failed to load integration for translation: Invalid domain energy.sensor
2025-08-02 17:59:25.379 WARNING (MainThread) [homeassistant.helpers.translation] Failed to load integration for translation: Invalid domain cloud.tts
2025-08-02 17:59:25.380 WARNING (MainThread) [homeassistant.helpers.translation] Failed to load integration for translation: Invalid domain shelly.light
2025-08-02 17:59:25.380 WARNING (MainThread) [homeassistant.helpers.translation] Failed to load integration for translation: Invalid domain shelly.button
2025-08-02 17:59:25.380 WARNING (MainThread) [homeassistant.helpers.translation] Failed to load integration for translation: Invalid domain shelly.climate
2025-08-02 17:59:25.380 WARNING (MainThread) [homeassistant.helpers.translation] Failed to load integration for translation: Invalid domain shelly.text
2025-08-02 17:59:25.380 WARNING (MainThread) [homeassistant.helpers.translation] Failed to load integration for translation: Invalid domain shelly.binary_sensor
2025-08-02 17:59:25.380 WARNING (MainThread) [homeassistant.helpers.translation] Failed to load integration for translation: Invalid domain shopping_list.todo
2025-08-02 17:59:25.381 WARNING (MainThread) [homeassistant.helpers.translation] Failed to load integration for translation: Invalid domain cast.media_player
2025-08-02 17:59:25.381 WARNING (MainThread) [homeassistant.helpers.translation] Failed to load integration for translation: Invalid domain hassio.sensor
2025-08-02 17:59:25.381 WARNING (MainThread) [homeassistant.helpers.translation] Failed to load integration for translation: Invalid domain sun.sensor
2025-08-02 17:59:25.381 WARNING (MainThread) [homeassistant.helpers.translation] Failed to load integration for translation: Invalid domain shelly.update
2025-08-02 17:59:25.381 WARNING (MainThread) [homeassistant.helpers.translation] Failed to load integration for translation: Invalid domain shelly.event
2025-08-02 17:59:25.382 WARNING (MainThread) [homeassistant.helpers.translation] Failed to load integration for translation: Invalid domain google_translate.tts
2025-08-02 17:59:25.382 WARNING (MainThread) [homeassistant.helpers.translation] Failed to load integration for translation: Invalid domain shelly.select
2025-08-02 17:59:25.383 WARNING (MainThread) [homeassistant.helpers.translation] Failed to load integration for translation: Invalid domain met.weather
2025-08-02 17:59:25.383 WARNING (MainThread) [homeassistant.helpers.translation] Failed to load integration for translation: Invalid domain shelly.switch
2025-08-02 19:02:41.013 ERROR (MainThread) [aiohttp.server] Error handling request from 172.30.32.2
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 510, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_app.py", line 569, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 41, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/hassio/addon_panel.py", line 61, in post
    await _register_panel(self.hass, addon, data)
  File "/usr/src/homeassistant/homeassistant/components/hassio/addon_panel.py", line 83, in _register_panel
    await panel_custom.async_register_panel(
    ...<9 lines>...
    )
  File "/usr/src/homeassistant/homeassistant/components/panel_custom/__init__.py", line 125, in async_register_panel
    frontend.async_register_built_in_panel(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        hass,
        ^^^^^
    ...<6 lines>...
        config_panel_domain=config_panel_domain,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/components/frontend/__init__.py", line 316, in async_register_built_in_panel
    raise ValueError(f"Overwriting panel {panel.frontend_url_path}")
ValueError: Overwriting panel a0d7b954_vscode
2025-08-02 19:52:40.438 ERROR (MainThread) [homeassistant.components.hassio.http] Client error on api app/frontend_latest/3807.36eea0243e5a4f5e.js request Cannot write to closing transport
2025-08-02 19:52:58.413 ERROR (MainThread) [homeassistant.components.hassio.http] Client error on api app/frontend_latest/3895.a5664826adcb2e23.js request Cannot write to closing transport
2025-08-02 19:52:58.442 ERROR (MainThread) [homeassistant.components.hassio.http] Client error on api app/frontend_latest/4440.d6399d2127436f60.js request Cannot write to closing transport
2025-08-02 19:52:58.466 ERROR (MainThread) [homeassistant.components.hassio.http] Client error on api app/frontend_latest/4274.8194bc886f4af440.js request Cannot write to closing transport
